apiVersion: v1
kind: Service
metadata:
  name: {{ include "goldpinger.fullname" . }}
  labels:
    {{- include "goldpinger.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "goldpinger.selectorLabels" . | nindent 4 }}
